title: McKenna Myckowiak
logo: mckennaheadshot.jpg
description: Contact Information <br/>
616 240-5756 | myckowiakmckenna@gmail.com | [LinkedIn](https://www.linkedin.com/in/mckenna-myckowiak-631169230/) 
theme: jekyll-theme-minimal
